version: "3.5"

services:
  metrics_portal_build:
    image: openbookpublishers/metrics_portal
    container_name: "metrics_portal_build"
    volumes:
      - dist:/usr/src/app/dist
    env_file:
      - ./.env

  metrics_portal_web:
    image: nginx
    container_name: "metrics_portal_web"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/portal.conf
      - ./site.conf:/etc/nginx/snippets/site.conf
      - dist:/usr/share/nginx/html:ro
    env_file:
      - ./.env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/portal.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

volumes:
  dist:
